<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { deleteMemory, listMemories } from '@/api/client'
import type { MemoryRecord } from '@/types'

const tenantId=ref('tenant_001');const records=ref<MemoryRecord[]>([]);const loading=ref(false);const error=ref('')
const activeCount=computed(()=>records.value.filter(r=>r.status==='active').length)
const quarantinedCount=computed(()=>records.value.filter(r=>r.status==='quarantined').length)
async function load(){loading.value=true;error.value='';try{records.value=(await listMemories(tenantId.value)).items}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function remove(record:MemoryRecord){await ElMessageBox.confirm('删除后会同步清理语义索引，但保留审计状态。','删除长期记忆',{type:'warning'});await deleteMemory(record.id,tenantId.value);ElMessage.success('记忆已标记删除');await load()}
function tone(status:string){return status==='active'?'success':status==='quarantined'?'warning':status==='deleted'?'danger':'info'}
onMounted(load)
</script>
<template><div class="memory-page"><section class="memory-summary"><article><span>记忆总数</span><strong>{{records.length}}</strong></article><article><span>有效记忆</span><strong>{{activeCount}}</strong></article><article><span>隔离区</span><strong>{{quarantinedCount}}</strong></article></section><section class="surface memory-surface"><header class="memory-header"><div><p>Tenant-scoped episodic memory</p><h2>来源、重要性、TTL 和删除状态</h2></div><div class="memory-actions"><el-input v-model="tenantId" aria-label="Tenant ID"/><el-button :loading="loading" @click="load"><el-icon><Refresh /></el-icon>刷新</el-button></div></header><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"/><el-empty v-else-if="!loading&&records.length===0" description="当前租户没有长期记忆"/><div v-else class="memory-list"><article v-for="record in records" :key="record.id"><div class="memory-main"><div class="memory-title"><strong>{{record.memory_key}}</strong><el-tag :type="tone(record.status)" effect="plain">{{record.status}}</el-tag></div><p>{{record.content}}</p><div class="memory-meta"><span>Case {{record.case_id}}</span><span>重要性 {{record.importance_score.toFixed(2)}}</span><span>访问 {{record.access_count}}</span><span>TTL {{record.expires_at??'永久'}}</span></div><div class="provenance"><span v-for="event in record.provenance_event_ids" :key="event">{{event}}</span></div></div><el-button circle title="删除记忆" :disabled="record.status==='deleted'" @click="remove(record)"><el-icon><Delete /></el-icon></el-button></article></div></section></div></template>
<style scoped>.memory-page{display:grid;gap:16px}.memory-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.memory-summary article{min-height:90px;padding:16px;border:1px solid var(--color-border);background:#fff}.memory-summary span{display:block;color:var(--color-muted);font-size:12px}.memory-summary strong{display:block;margin-top:12px;font-size:26px}.memory-surface{padding:20px}.memory-header{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}.memory-header p{color:var(--color-muted);font-size:12px;margin-bottom:4px}.memory-header h2{font-size:19px}.memory-actions{display:flex;gap:8px}.memory-list{display:grid;gap:1px;background:var(--color-border-soft);border:1px solid var(--color-border-soft)}.memory-list>article{background:#fff;padding:16px;display:flex;justify-content:space-between;gap:14px}.memory-title{display:flex;gap:8px;align-items:center}.memory-main p{margin:8px 0;color:#354354;line-height:1.6}.memory-meta,.provenance{display:flex;flex-wrap:wrap;gap:6px}.memory-meta span,.provenance span{padding:3px 7px;background:#f1f4f6;color:var(--color-muted);font-size:11px;border-radius:3px}.provenance{margin-top:8px}.provenance span{background:#e7f2ef;color:#236553}@media(max-width:700px){.memory-summary{grid-template-columns:1fr 1fr 1fr}.memory-header{align-items:flex-start;flex-direction:column}.memory-actions{width:100%}.memory-list>article{align-items:flex-start}}</style>
